AWSTemplateFormatVersion: '2010-09-09'
Description: Upload files to S3 via pre-signed URLs

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: youtube-path-watch-histories-611312332993-eu-central-1
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "https://my-youtube-path.com"
              - "http://localhost:3000"
            AllowedMethods:
              - "PUT"
            AllowedHeaders:
              - "*"
            MaxAge: 3000

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: YouTubePathFileUploadLambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${UploadBucket}/*'
        - PolicyName: LambdaCloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/PreSignedUrlFunction:*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/PreSignedUrlFunction:*:log-stream:*'

  PreSignedUrlFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs24.x
      Code:
        ZipFile: |
          const { S3Client, PutObjectCommand } = require("@aws-sdk/client-s3");
          const { getSignedUrl } = require("@aws-sdk/s3-request-presigner");

          const s3Client = new S3Client({ region: "eu-central-1" });

          exports.handler = async (event) => {
            const timestamp = new Date().getTime();
            const fileName = `watch-history-${timestamp}.json`;

            const command = new PutObjectCommand({
              Bucket: 'youtube-path-watch-histories-611312332993-eu-central-1',
              Key: fileName,
              ContentType: 'application/json',
              ACL: 'private',
            });

            const allowedOrigins = ["https://my-youtube-path.com", "http://localhost:3000"];
            const origin = event.headers.origin;
            let headers = {
              "Content-Type": "application/json"
            };

            if (allowedOrigins.includes(origin)) {
              headers["Access-Control-Allow-Origin"] = origin;
            }

            try {
              const preSignedUrl = await getSignedUrl(s3Client, command, { expiresIn: 3600 });
              return {
                statusCode: 200,
                headers: headers,
                body: JSON.stringify({ uploadURL: preSignedUrl, fileName })
              };
            } catch (err) {
              return {
                statusCode: 500,
                body: JSON.stringify({ error: "Error creating pre-signed URL" })
              };
            }
          };

      FunctionName: PreSignedUrlFunction

  ApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: PreSignedURLAPI
      Description: API Gateway to generate pre-signed URLs
      FailOnWarnings: 'true'
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        swagger: "2.0"
        info:
          title: "PreSignedURLService"
        paths:
          /generate-url:
            post:
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                '200':
                  description: "Successful response"
                  schema:
                    type: object
                    properties:
                      uploadURL:
                        type: string
                      fileName:
                        type: string
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PreSignedUrlFunction.Arn}/invocations
            options:
              consumes:
                - application/json
              produces:
                - application/json
              responses:
                '200':
                  description: "200 response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: "string"
                    Access-Control-Allow-Methods:
                      type: "string"
                    Access-Control-Allow-Headers:
                      type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Methods: "'POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Origin,Accept'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                requestTemplates:
                  application/json: "{\"statusCode\": 200}"
                passthroughBehavior: "when_no_match"
                type: "mock"

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
    DependsOn: PreSignedUrlFunction

  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      StageName: prod
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiGatewayDeployment
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          ThrottlingBurstLimit: 2
          ThrottlingRateLimit: 1

  LambdaApiGatewayInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PreSignedUrlFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/*'

  ApiGatewayCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: file-upload.my-youtube-path.com
      # Certificate for file-upload.my-youtube-path.com in eu-central-1
      RegionalCertificateArn: arn:aws:acm:eu-central-1:611312332993:certificate/80ff25a0-881d-4493-92d2-2f02f9424013
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
      - ApiGatewayCustomDomain
      - ApiGatewayStage
    Properties:
      DomainName: file-upload.my-youtube-path.com
      RestApiId: !Ref ApiGateway
      Stage: prod

  FileUploadApiDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: "Z06009411YUFOH75I3G4S" # hosted zone ID of my-youtube-path.com
      Name: file-upload.my-youtube-path.com
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt ApiGatewayCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt ApiGatewayCustomDomain.RegionalDomainName
