AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Next.js application infrastructure.

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: youtube-path-611312332993-eu-central-1
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${SiteBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt SiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - my-youtube-path.com
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          # Certificate for my-youtube-path.com in us-east-1
          AcmCertificateArn: arn:aws:acm:us-east-1:611312332993:certificate/4a391dcc-39a7-4ee7-903d-f81d1ed6834d
          SslSupportMethod: sni-only

  MyRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: "Z06009411YUFOH75I3G4S" # hosted zone ID of my-youtube-path.com
      Name: my-youtube-path.com.
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # this is the zone ID for CloudFront distributions
        DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  SiteURL:
    Description: "URL of the S3 bucket hosting the site."
    Value: !GetAtt SiteBucket.WebsiteURL
  CloudFrontDistributionId:
    Description: "The CloudFront Distribution ID."
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomainName:
    Description: "The domain name of your CloudFront distribution."
    Value: !GetAtt CloudFrontDistribution.DomainName
  RecordSet:
    Description: "The record set for the custom domain."
    Value: !Ref MyRecordSet
