AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFront Configuration for PostHog as a Reverse Proxy

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: eu.i.posthog.com
            Id: PostHogOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
          - DomainName: eu-assets.i.posthog.com
            Id: AssetsOrigin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: PostHogOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: !Ref CachePolicy
          OriginRequestPolicyId: "59781a5b-3903-41f3-afcb-af62929ccde1" # CORS-CustomOrigin
          ResponseHeadersPolicyId: "e61eb60c-9c35-4d20-a928-2b84e02af89c" # CORS-and-SecurityHeadersPolicy
        CacheBehaviors:
          - PathPattern: /static/*
            TargetOriginId: AssetsOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD, OPTIONS]
            CachePolicyId: !Ref CachePolicy
            OriginRequestPolicyId: "59781a5b-3903-41f3-afcb-af62929ccde1" # CORS-CustomOrigin
            ResponseHeadersPolicyId: "e61eb60c-9c35-4d20-a928-2b84e02af89c" # CORS-and-SecurityHeadersPolicy

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: origin-cors
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Origin
              - Authorization
          QueryStringsConfig:
            QueryStringBehavior: all
          CookiesConfig:
            CookieBehavior: none

Outputs:
  CloudFrontURL:
    Description: The URL of the CloudFront Distribution
    Value: !GetAtt CloudFrontDistribution.DomainName
