name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js Application
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy CloudFormation Template
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/template.yaml \
            --stack-name YoutubePath \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get Bucket Name from CloudFormation Output
        id: get-bucket-name
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name YoutubePath --query "Stacks[0].Outputs[?OutputKey=='SiteBucketName'].OutputValue" --output text)
          echo "Bucket name is $BUCKET_NAME"
          echo "::set-output name=bucket_name::$BUCKET_NAME"

      - name: Sync Files to S3 Bucket
        run: |
          aws s3 sync ./out s3://${{ steps.get-bucket-name.outputs.bucket_name }} --delete
